
version: '3.3'


services:

   jatos-backend:
     image: jatos/jatos:2.2.4
     ports:
       - "9000:9000"
     env_file:
       - backend-variables.env

   nginx:
     depends_on:
       - jatos-backend
     image: nginx:1.19
     ports:
       - "80:80"
       - "443:443"
     environment:
       VIRTUAL_HOST_OR_SOMETHING: jatos.mola.com


volumes:
    db_data: 


